language: python

python:
  - 3.3
  - 3.4

env:
  - DJANGO='Django>=1.7,<1.8'
  - DJANGO=https://github.com/django/django/archive/master.zip

install:
  - pip install "$DJANGO"
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database golgoth;' -U postgres

script:
  - ./runtests.sh

deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password:
    secure: $OPENSHIFT_PASSWORD
  app: $OPENSHIFT_APP_NAME
  domain: $OPENSHIFT_APP_NAMESPACE
  on:
    repo: golgoth42/golgoth
