language: python

python:
  - 3.3
  - 3.4

env:
  - PYTHON_PROD=3.3
  - DJANGO_PROD=1.7.1
  - DJANGO_MASTER=https://github.com/django/django/archive/master.zip
  - DJANGO=$DJANGO_PROD
  - DJANGO=$DJANGO_MASTER

install:
  - pip install "Django==$DJANGO"
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database golgoth;' -U postgres

script:
  - ./runtests.sh

deploy:
  provider: openshift
  user: $OPENSHIFT_USERNAME
  password:
    secure: $OPENSHIFT_PASSWORD
  app: $OPENSHIFT_APP_NAME
  domain: $OPENSHIFT_APP_NAMESPACE
  on:
    python: $PYTHON_PROD
    condition: $DJANGO = $DJANGO_PROD
    repo: golgoth42/golgoth
